// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJ-9GrTbWf5_VkqykD89llN64H5rWXtA',
    appId: '1:246196822761:web:380c48a263f53363b2c678',
    messagingSenderId: '246196822761',
    projectId: 'elearning-8b084',
    authDomain: 'elearning-8b084.firebaseapp.com',
    storageBucket: 'elearning-8b084.appspot.com',
    measurementId: 'G-TYRBXHXPMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBL7BOmJtEuCvHvbVj3brQz8FxesEjuI',
    appId: '1:246196822761:android:ceb0b8cf8d17e19fb2c678',
    messagingSenderId: '246196822761',
    projectId: 'elearning-8b084',
    storageBucket: 'elearning-8b084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrL0Q2Q_oVcYElFXNeYEsuXSRLVirHU1w',
    appId: '1:246196822761:ios:330bf2a956ef2edab2c678',
    messagingSenderId: '246196822761',
    projectId: 'elearning-8b084',
    storageBucket: 'elearning-8b084.appspot.com',
    iosClientId: '246196822761-rj700eiaonpbm9mnnamc594nba1midu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrL0Q2Q_oVcYElFXNeYEsuXSRLVirHU1w',
    appId: '1:246196822761:ios:2b4eba6ea51889fab2c678',
    messagingSenderId: '246196822761',
    projectId: 'elearning-8b084',
    storageBucket: 'elearning-8b084.appspot.com',
    iosClientId: '246196822761-jht41qmvtaf426dono4t5njn89qes5c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
